### ISSUE TITLE
ImportError: No module named fontTools.ttLib

### ISSUE THREAD

**Issue by ldjqust** [bob-chen/react-native-iconfont-mapper#3]
1. pip install fonttools
2.python iconfont-mapper.py iconfont.ttf iconfont.js
3.Traceback (most recent call last):
  File "iconfont-mapper.py", line 5, in <module>
    from fontTools.ttLib import TTFont
ImportError: No module named fontTools.ttLib

**Comment by tourze** [comment]
执行 `pip install fontTools`

**Comment by bob-chen** [comment]
先确定 fontTools 是否安装成功
