### ISSUE TITLE
我通过pyrhon命令执行该文件的生活报语法错误

### ISSUE THREAD

**Issue by Liyi-up** [bob-chen/react-native-iconfont-mapper#6]
D:\WebCode\RNCode\自定义图标\react-native-iconfont-mapper>python iconfont-mapper.py iconfont.ttf iconfont.js
  File "iconfont-mapper.py", line 24
    except Exception, ex:
                    ^
SyntaxError: invalid syntax

**Comment by xSeek-Neo** [comment]
I have seem question

**Comment by bob-chen** [comment]
Fixed, compatibility issues between different python versions
